export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import SessionProvider from "@/lib/SessionProvider"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
      <body>{children}</body>
      </SessionProvider>
    </html>
  )
}
